## Understanding NUMPY

## ARRAY PROPERTIES

In [3]:
import numpy as np
# Creating a NumPy array using arange
a = np.arange(1,16).reshape(3, 5)

print("Array a:")
print(a)
print()

# ---------------------------------------
# Array Properties
# ---------------------------------------

# Shape of the array (rows, columns)
print("Shape of array a:", a.shape)

# Number of dimensions
print("Number of dimensions (ndim):", a.ndim)

# Data type of elements
print("Data type:", a.dtype.name)

# Size (in bytes) of one element
print("Item size (bytes):", a.itemsize)

# Total number of elements
print("Total number of elements:", a.size)

# Type of variable
print("Type of a:", type(a))


Array a:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Shape of array a: (3, 5)
Number of dimensions (ndim): 2
Data type: int64
Item size (bytes): 8
Total number of elements: 15
Type of a: <class 'numpy.ndarray'>


## ARRAY CREATION

In [4]:

import sys
from numpy import pi

# Print full NumPy arrays (no truncation)
np.set_printoptions(threshold=sys.maxsize)

a = np.array([2, 3, 4])
print("Array a:", a)
print()


#  Multi-Dimensional Array (2D)

b_2d = np.array([(1.5, 2, 3), (4, 5, 6)])
print("2D Array:\n", b_2d)
print("Dimensions:", b_2d.ndim)
print()


# Explicit Data Type Specification
c = np.array([[1, 2], [3, 4]], dtype=complex)
print("Complex Array:\n", c)
print("Data type:", c.dtype)
print()



Array a: [2 3 4]

2D Array:
 [[1.5 2.  3. ]
 [4.  5.  6. ]]
Dimensions: 2

Complex Array:
 [[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
Data type: complex128



## TO MAKE A ARRAY

In [12]:


# Empty array (random memory values)
empty_arr = np.empty((2, 3))
print("Empty Array (uninitialized):\n", empty_arr)
print()


float_range = np.arange(0, 2, 0.3)
print("Arange with floats:", float_range)
print()

# Using linspace() (Preferred for floats)
lin_arr = np.linspace(0, 2, 10)
print("Linspace array:", lin_arr)
print()



Empty Array (uninitialized):
 [[0.3 0.6 0.9]
 [1.2 1.5 1.8]]

Arange with floats: [0.  0.3 0.6 0.9 1.2 1.5 1.8]

Linspace array: [0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]



## MATRIX MULATIPLIACTAION 

In [14]:
a = np.array([[1, 1],
            [0, 1]])
b = np.array([[2, 0],
            [3, 4]])
print(a*b)  # elementwise product
print(a@b) #matrix multiplication
print(a.dot(b)) #another way to write multiplication of matrix

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


## TO TAKE RANDOM VARIABLES 

In [ ]:

rg = np.random.default_rng(1) # always same after the execution 
print(rg.random())        # random float in [0, 1)
print(rg.integers(1, 10)) # random integer between 1 and 9
rg.random((2, 3))


In [ ]:
full=np.full((2,3),7)
full
random=np.random.random((1,5))
random

## ARRAY RESHAPING

In [ ]:
arr=np.arange(1,13)
print("original array", arr)

reshape=arr.reshape((3,4))
print("Reshaped array", reshape)

flattened=reshape.flatten()   #retures the copy of the array 
print("flattened array", flattened)


#ravel(returs view,insted of copy)
raveled=reshape.ravel()
print("raveled array",raveled)

transpose=reshape.T
print("transpose array", transpose)


## ARRAY OPERATIONS 

 Indexing in 1D array

In [ ]:
arr=np.arange(1,11)
print("indexing ",arr[0:5])
print ("with step",arr[1:10:2])
print(" Negative indexing ",arr[-1])

indexing in 2 D array

In [ ]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("specific element:",arr2d[0,2])
print("entier row:" ,arr2d[1])
print("entier column:" ,arr2d[:,1])

## SORTING

In [10]:
unsorted=np.array([3,56,47,4,5,4,5,3,86,89,54,51,4,51])
print("sorted array", np.sort(unsorted))
arr2d=np.array([[1,13,2],[4,51,6],[7,8,79]])
print("sorted  2D array column", np.sort(arr2d,axis=0))# sorted by colums 
print("sorted  2D array row", np.sort(arr2d,axis=1))

sorted array [ 3  3  4  4  4  5  5 47 51 51 54 56 86 89]
sorted  2D array column [[ 1  8  2]
 [ 4 13  6]
 [ 7 51 79]]
sorted  2D array row [[ 1  2 13]
 [ 4  6 51]
 [ 7  8 79]]


## FILTER

In [8]:
numbers=np.arange(1,11)
even_number=numbers[numbers%2==0]
print("even numbers:",even_number)

even numbers: [ 2  4  6  8 10]


 Filter with mask

In [6]:
mask= numbers>5
print("numbers greater than 5 :",numbers[mask])

NameError: name 'numbers' is not defined

## FANCY INDEXING VS NP.WHERE()

In [ ]:
indices=[0,2,3]
print(numbers[indices])

where_result= np.where(numbers>5) #store the index
print(where_result)
print()
print("np.where",numbers[where_result])

In [ ]:
condition=np.where(numbers>5,"True","False")
print(condition)

## ADDING AND REMOVING ARRAY

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.concatenate((arr1,arr2)))

In [ ]:
#array compatibility
a=np.array([1,2,3])
b=np.array([4,5,6,7])
c=np.array([11,32,35])
print("Compatibility shapes", a.shape==b.shape)
print("Compatibility shapes", a.shape==c.shape)

In [ ]:
original=np.array([[1,2],[3,4]])
row=np.array([[12,27]])
column=np.array([[7],[9]])
print(np.vstack((original,row)))
print(np.hstack((original,column)))

In [ ]:
arr=np.array([1,2,3,4,5])
print(np.delete(arr,2))